### ISSUE TITLE
Sync error invalid wal header magic: 0

### ISSUE THREAD

**Issue by olivierdeckers** [benbjohnson/litestream#220]
When running litestream in a docker container and an sqlite3 process on MacOS 11.2.2, I sometimes get into a situation where litestream keeps logging 

> /data/test.db: sync error: create generation: initialize shadow wal: invalid wal header magic: 0

I haven't been able to consistently reproduce this, but it seems to be triggerd by the sqlite3 process being stopped. When it starts logging this line, restarting litestream causes it to log this message:

> /data/test.db: init: cannot determine last wal position, clearing generation; wal header mismatch 0000000000000000000000000000000000000000000000000000000000000000 <> 377f0682002de21800001000000000007497411e1043038df3289a873813b53c on /data/.test.db-litestream/generations/8b0891959e88d8fc/wal/00000000.wal

After that, it keeps logging the `invalid header magic: 0` message. I've seen it recover after some time, where it says `/data/test.db: sync: new generation "743b12d2fc79a1fd", no generation exists`

I have a feeling this might be due to docker volume mounting on MacOS not working as well as expected. I've encountered other weird behavior while trying to reproduce this where litestream would hang while starting. When this happened, running `docker exec container ls /data`, would hang as well.

**Comment by benbjohnson** [comment]
@olivierdeckers Thanks for reporting the issue. I investigated it and it looks like it's failing because the locking mechanisms are different between the host (`macOS`) & the container (`Linux`). SQLite will checkpoint the WAL file into the main DB file when it closes if there are no other processes also using the database at the same time. It checks for other processes using the kernel lock mechanisms (e.g. `fcntl`) but that doesn't work if they're different OSes.

I tried running `sqlite3` in one container and `litestream` in a different container that both use a shared volume and it seems to work fine:

```sh
# Run Litestream in one container
$ docker run -v /data:/data -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY litestream/litestream replicate /data/db s3://MYBUCKET/db
```

and then:

```sh
# Run bash in Ubuntu in a different container
$ docker run -it -v /tmp/data:/data ubuntu /bin/bash
root# apt update && apt install -y sqlite3
root# sqlite3 /data/db
sqlite> CREATE TABLE t (x);
sqlite> INSERT INTO t (x) VALUES (1);
sqlite> .quit
```

I added a warning message at the top of the Docker guide on the Litestream web site so folks are aware: https://litestream.io/guides/docker/

<img width="663" alt="Screen Shot 2021-06-25 at 3 31 05 PM" src="https://user-images.githubusercontent.com/118015/123487012-5d475c80-d5ca-11eb-87a0-fd1f2fa34590.png">
