### ISSUE TITLE
Can litestream be used for multi master replication?

### ISSUE THREAD

**Issue by DoobleD** [benbjohnson/litestream#228]
Hi folks. Litestream looks great, nice work!

I'm wondering if it can be used for master master replication? For instance say I have two servers named `A` and `B` with each a local copy of the same sqlite database. Can `A` replicate any local change to `B` and `B` replicate any local change to `A` simultaneously?

I suppose this could work only if each replica makes sure all other replicas have applied a query before applying it locally. Otherwise replicas could start diverging, I think. 

For instance if server `A` makes a local update based on a `WHERE` clause on the value of column `C`, but server `B` has changed the value of column `C` locally before the update from `A` is received. In that case the update from `A` doesn't work on `B`, whereas it did work on `A`.

Disclaimer: I know nothing about replication, just thinking out loud here.

**Comment by benbjohnson** [comment]
Hi @DoobleD, good question. Multi-master replication is generally a lot harder than primary-replica replication because you get into consistency issues and conflict resolution. You also have trade-offs with regards to performance if you're doing something like a two-phase commit. So, to answer your question, no, Litestream doesn't support multi-master replication. It's also not likely to be a goal of the project in the future.

**Comment by DoobleD** [comment]
Thank you for the prompt and complete answer @benbjohnson, I appreciate it!

**Comment by aguynamedben** [comment]
@benbjohnson Have you seen anybody building a CRDT layer on top of SQLite + litestream? I'm curious if a desktop app uses SQLite if it could sync it up to a server, then the server could run a few INSERT queries and have those sent back down to the SQLite database on the client. That's basically multi-master replication, right? It seems like litestream is 1-way replication, and it seems like rqlite is fully distributed but as you mention I think that writes require a check with a (potentially high latency) leader.

I'm just learning about the CRDT pattern now, but it seems like someone could make a thin CRDT layer on top of SQLite.

Disclaimer: like the OP @DoobleD, I also know nothing about replication, just thinking out loud here :)

**Comment by benbjohnson** [comment]
@aguynamedben Good question. Litestream isn't able to work with raw INSERT statements because it implements physical replication (meaning it replicates the raw pages). You could implement something like CRDTs at a higher level on top of SQLite. You may also want to look at the [session extension](https://www.sqlite.org/sessionintro.html) which allows you to replicate changesets and you might get something CRDT-like with that.

**Comment by aguynamedben** [comment]
Thanks for the info!
