### ISSUE TITLE
`/generations/x/wal/y.lz4` overflow?

### ISSUE THREAD

**Issue by broccolihighkicks** [benbjohnson/litestream#325]
One of my processes updates a `heartbeat` cell in a SQLite database a few times a second (so that other processes can determine it is still being written to).

Will this cause any issues with litestream?

I see that it will generate many wal files which would slow the restore down, but would any internal litestream counters overflow by having too many `/generations/x/wal/y.lz4` - say for instance my process ran for a few years with multiple updates per second?

Thanks.

**Comment by benbjohnson** [comment]
Thanks for submitting the ticket. Theoretically it could overflow eventually although that would be a lot of WAL files. The index rolls over ever minute at a minimum and the upper bound on the index encoding is 2^32 so that's something like 8,000 years. However, I did recently adjust the encoding so that it holds 2<64 for both the index & offset since a WAL could be larger than 2GB which would exceed the offset. You can find the PR here: https://github.com/benbjohnson/litestream/pull/309
