### ISSUE TITLE
Manual restore?

### ISSUE THREAD

**Issue by orent** [benbjohnson/litestream#406]
Can I restore a replica manually with nothing but cp, unlz4 and cat?

I know litestream has a perfectly capable restore command, but it can be reassuring to know how things work under the hood.

**Comment by benbjohnson** [comment]
Hi @orent. Yep. The restore process isn't too complicated. It's just a couple steps:

1. Download the snapshot to a local file (say, `db`)
2. Download all the WAL segments at or after that index
3. For each WAL index, `cat` together all WAL segments in order to the WAL location next to the DB file (`db-wal`)
4. Execute for each WAL file built: `sqlite3 db "PRAGMA wal_checkpoint(TRUNCATE)"`

So if you have snapshot called `0000000000000005.snapshot.lz4` and the following WAL segments:

```
wal/0000000000000005_0000000000000000.wal.lz4
wal/0000000000000005_0000000000002050.wal.lz4
wal/0000000000000006_0000000000000000.wal.lz4
```

you would `cat` the two `0000000000000005` WAL files together to `db-wal`, execute the checkpoint, then `cat` the `0000000000000006` WAL file to `db-wal`, and checkpoint.
